# Declarative vs Imperative

We'll demonstrate the concepts of declarative vs imperative programming with one siple example: computing the product of a matrix and a vector:

\begin{equation*}
\begin{bmatrix}
    1       & -1 & 2 \\
    0       & -3 & 1\\
\end{bmatrix} \cdot \begin{bmatrix}2 \\ 1 \\ 0\end{bmatrix}
=
\begin{bmatrix}1 \\ -3\end{bmatrix}
\end{equation*}

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [0, -3, 1]
])
A

array([[ 1, -1,  2],
       [ 0, -3,  1]])

In [3]:
x = np.array([2, 1, 0])
x

array([2, 1, 0])

### Imperative solution

The imperative solution in this example will be verbose and filled with side effects, take a look:

In [4]:
result = []
row_count = 0

for row in A:
    partial_result = 0
    for i in range(len(row)):
        a_elem = row[i]
        x_elem = x[i]
        partial_result += (a_elem * x_elem)
    result.append(partial_result)
    row_count += 1

result

[1, -3]

It works, but it's really hard to understand and debug. Picture reading that code without any sort of context. Would it be evident that we're doing a matrix-vector product?

### Declarative solution

This one is a lot easier to read and understand, we're leveraging the high abstraction level provided by both Python and Numpy in order to compute it:

In [5]:
A @ x

array([ 1, -3])

In [6]:
np.dot(A, x)

array([ 1, -3])

Both work, you can use either. The `@` operator was [introduced in Python 3.5](https://docs.python.org/3/whatsnew/3.5.html#pep-465-a-dedicated-infix-operator-for-matrix-multiplication), `np.dot` is a core numpy function.